# ŞEKİLLER LİSTESİ {-}

**Şekil 1.1:**  Halkla İlişkilerde Olayları ve Kişileri Tanımlama Zaman Çizelgesi	9

**Şekil 1.2:** Halkla İlişkiler Stratejik Yönetim Modeli	12

**Şekil 1.3:** Phillips'in Dijital İletişim Araçları Modeli	30

**Şekil 2.1:** İklim Değişikliği ve Küresel Isınma Tweet Karşılaştırması	38

**Şekil 2.2:** İklim Değişikliği Konulu Uluslararası Görüşmeler Sürecindeki Önemli Dönüm Noktaları ve Gelişmeler	40

**Şekil 2.3:** Afet Türü Başına Ölüm Sayısı	45

**Şekil 2.4:** Polanyi: Ekonomiler Farklı Toplumlarda Nasıl Farklı Kurulmaktadır?	72

**Şekil 2.5:** Toplumlar Farklı Kaynak Ortamlarında Nasıl Farklı Yapılandırılmıştır?	73

**Şekil 2.6:** Ulusal Zenginlik ve İklim Değişikliği	74

**Şekil 3.1:** Çevresel İletişim Bilgi Modeli	81

**Şekil 3.2:** İletişim Sürecinin Ekolojik Modeli	83

**Şekil 3.3:** Yönetişimin Paydaş ve Araçları	100

**Şekil 3.4:** İklim Değişikliği Yönetişimi Aktörleri	102

**Şekil 3.5:** Derneklerin Faaliyet Alanların Göre Dağılımı	108

**Şekil 4.1:** CRISP Veri Madenciliği Süreci	120

**Şekil 4.2:** Veri Yöntemleri Olarak Metne Genel Bakış	123

**Şekil 4.3:** Sivil Toplum Kuruluşları Tweet Sayısı 2020-2021	126

**Şekil 4.4:** Bakanlıklar Tweet Sayısı 2020-2021	127

**Şekil 4.5:** 2020-2021 Çevre ve İklim Tweetlerin Tematik Oransal Dağılımı	140

**Şekil 4.6:** Çok Boyutlu Ölçekleme Yoluyla Konular Arası Mesafe Haritası	141

