


# ÖZ {-}

**HALKLA İLİŞKİLER VE İKLİM DEĞİŞİKLİĞİ: BAKANLIKLARIN VE STK'LARIN TWİTTER ÜZERİNDEKİ HALKLA İLİŞKİLER FAALİYETLERİNİN KARŞILAŞTIRILMASI**

**KEMAL GÜNAY**
 
 
İklim değişikliği, hem hükümetler için en acil kamu sorunu hem de insanlığın yaşadığı en ağır varoluşsal kriz olarak önümüze çıkmaktadır. Petrol, kömür ve doğal gazın enerji üretmek için yakılması, hapsolmuş karbondioksit ve diğer sera gazlarının dünyamızın bütün bölgelerindeki ortalama sıcaklıkları yükseltmesine sebep olmaktadır. Bu, sıcak hava dalgaları, aşırı yoğun yağışlar, kuraklık, deniz seviyesinin yükselmesi, biyoçeşitlilik kayıpları gibi sorunların ortaya çıkmasına sebep olmaktadır. Bu durumlar, gıda güvenliği, sağlık, su kaynakları gibi sorunları da beraberinde getirmektedir.

İklim değişikliği, zaman zaman insanlığın gündemine gelse de birçok insan için kolay algılanmayan karmaşık bir konudur. Bu noktada, problemin ve çözüm yollarının nasıl tasvir edildiği ve nasıl bir iletişim stratejisi kullanıldığı önemlidir. Kent ve Taylor, organizasyonların hedef gruplarıyla diyalojik iletişim kurmaları için web üzerinde bir çerçeve sunmaktadır. Bu iletişimi sağlamak için beş ilke belirlemişlerdir: Diyalojik döngü, bilginin kullanıma uygun olması, web için tekrar ziyaretçi dönüşümü, web arayüzünün kullanıcı dostu olması ve ziyaretçilerin korunması.

Grunig’e göre halkla ilişkiler; imaj, algı, mesajlaşma, itibar, marka, bütünleşmiş pazarlama iletişimi, yatırım getirisi (ROI), stratejik iletişim, kurumsal sosyal sorumluluk projeleri gibi kavramlara odaklanmaktadır. Halkla ilişkiler uygulayıcıları, yeni dijital medyayı; düşünme biçimlerini değiştiren ve halkla ilişkiler uygulamalarını şekillendiren devrim niteliğinde bir güç olarak görmektedir. Bu nedenle, organizasyonlar da halkla ilişkiler uygulamalarını, pazarlama faaliyetlerini ve diğer iletişimlerini sosyal ağlar üzerinden sağlamaktadır. Bu sebeple, Twitter önemli bir sosyal ağ uygulaması olarak karşımıza çıkmaktadır.

Twitter, üç nedenden dolayı tercih edilmiştir: 1) Küresel şirketler tarafından en yaygın kullanılan sosyal medya kanalı olması. 2) Diyalojik iletişim için kullanıcı etiketleme (mention), hashtag, medya, linkler gibi birçok faydalı özellik sunması. 3) Hemen hemen tüm kurumların Twitter sayfalarına herhangi bir kullanıcı tarafından erişilebilir olmasıdır. 

Araştırma kapsamında; öncelikli olarak iklim aktörlerinin iletişimlerinde halkla ilişkiler yaklaşımlarından olan diyalojik iletişimi ne ölçüde kullandığı ortaya konmuştur. Devamında, aktörlerin diyalojik iletişimleri kapsamında hedef kitlenin katılımı incelenmiştir. İkinci olarak, Grunig-Hunt’un dört halkla ilişkiler modeli bağlamında aktörlerin iletişimlerini nasıl konumlandırdıkları araştırılmıştır. Son olarak, Türkiye’de çevre ve iklim tartışmalarının hangi konular kapsamında tartışıldığı ortaya konmuştur. İklim değişikliği iletişimi, yurt dışı kaynaklarda birçok çalışmada yer almasına rağmen, ülkemizde henüz çok fazla çalışılmayan bir alandır. Çalışmanın bu kapsamda iklim değişikliği iletişimi alanına akademik yönelimi sağlaması beklenmektedir.

Bu çalışmada, birden fazla araştırma yaklaşımı kullanılmıştır. İçerik analizi yoluyla veriler tanımlanmış ve verilerden farklı değişkenler türetilmiştir. Veriler, belirli kavramlar ve temalar çerçevesinde bir araya getirilmiştir. Twitter uygulamasından elde edilen verilerden, kural tabanlı filtrelemeler yapılarak yeni değişkenler ortaya çıkartılmıştır. Bu yaklaşım, Twitter gibi hızlı veri akışlarının olduğu ortamlar için efektif bir şekilde içerik analizi yapmayı mümkün kılmakta; büyük veri setleri için diyalojik iletişim ve dört halkla ilişkiler modellerinin değerlendirilmesi açısından kural tabanlı bir yaklaşım sunmaktadır. Son olarak, çevreci sivil toplum kuruluşlarının 2020-2021 yıllarındaki paylaşımlarının hangi temalar kapsamında çerçevelendiği ve konu dağılımı ortaya çıkarılmıştır. Bu çerçevede, olasılıksal konu modelleme yaklaşımlarından Gizil Dirichlet Ayrımı (LDA) yöntemi kullanılmıştır. Bu araştırma ile yeni teknolojilerin halkla ilişkiler alanına uyarlanması noktasında öncü ve yenilikçi bir yaklaşım sunduğu düşünülmektedir.

Araştırma sonucunda hem sivil toplum kuruluşları hem de bakanlıklar için anahtar diyalojik ilkenin “Yeniden Ziyaretçi Sağlama” olduğu tespit edilmiştir. Kuruluşlar “ek bilgi veren siteleri” paylaşarak bunu sağlamaktadır. İkincil olarak “Bilginin Kullanımlığı” ilkesine ağırlık verildiği, bunu da organizasyonların “fotoğraf” paylaşımlarıyla yaptıkları tespit edilmiştir.  “Ziyaretçilerin Elde Tutulması” kriterinde ise, her iki aktör grubunun “kendi websiteleri paylaşımlarına” öncelik verdiği; STK’ların ise bakanlıklara göre daha çok “sosyal ağ paylaşımları” yaptığı ortaya çıkmıştır. Kuruluşların “Diyalojik Döngü” ilkesi kullanımlarında da belirgin farklılıklar olduğu gözlemlenmiştir. STK’lar “kullanıcıların cevaplanması” ve “hashtag kullanımı” özelliklerini daha fazla kullanırken, bakanlıklar ise “kullanıcı etiketleme” özelliğini daha fazla kullanmıştır. Kuruluşların diyalojik iletişim kapsamında kamu katılımının değerlendirildiği araştırmada; kuruluşların diyalojik iletişim ilkeleri kullanımları ve kamu katılımı arasında güçlü bir ilişki olduğu sonucu çıkmıştır. Grunig’in dört halkla ilişkiler modeli kapsamında yapılan araştırmada, STK’lar ve bakanlıkların Twitter kullanımlarında dört model kapsamında farklı model kullanımı sergiledikleri gözlemlenmiştir. Hem STK’lar hem de bakanlıkların “kamuoyu bilgilendirme” modeline ağırlık verdiği gözlemlenmiştir. İklim aktörlerinin en az kullandıkları modelin ise “simetrik” model olduğu tespit edilmiştir. Her iki aktör grubu sırasıyla, “kamuoyu bilgilendirme”, “asimetrik”, “basın ajansı” ve “simetrik” modelleri kullanmaktadır. Çevre ve iklim değişikliği üzerine Türkiye’de Twitter ortamında gerçekleştirilen paylaşımların 9 ana başlıkta kümelendiği gözlemlenmiştir. “Biyoçeşitlilik”, “iklim” ve “sürdürülebilirlik” temalarının diğer temalara göre daha ağırlıkta olduğu tespit edilmiştir. Literatürde yer aldığı gibi STK’ların iklim krizini ve bileşenlerini ana konular olarak tartıştığı ortaya çıkmıştır.

**Anahtar Kelimeler:** Halkla ilişkiler, iklim değişikliği iletişimi, iklim iletişimi, iklim krizi, çevre iletişimi, diyalojik iletişim, Grunig-Hunt dört halkla ilişkiler modeli, konu modelleme, gizil dirichlet ayrımı, metin sınıflandırma, hesaplamalı sosyal bilimler, Twitter, sivil toplum kuruluşları, bakanlıklar
