# ABSTRACT {-}

PUBLIC RELATIONS AND CLIMATE CHANGE: A COMPARISON OF MINISTRY AND NGO'S PUBLIC RELATIONS ACTIVITIES ON TWITTER
KEMAL GÜNAY

Climate change is emerging as both the most urgent public issue for governments and the most severe existential crisis faced by humanity. The burning of fossil fuels such as oil, coal, and natural gas is causing an increase in the levels of trapped carbon dioxide and other greenhouse gases, which is leading to rising temperatures in all regions of the world. This results in problems such as heat waves, heavy rains, droughts, sea level rises, and loss of biodiversity. These issues are also causing problems such as food security, health, and water resources.

Climate change is a complex issue that can be difficult for many people to understand. In this regard, it is important how the problem and solutions are portrayed and what communication strategy is used. Kent and Taylor propose a framework for organizations to engage in dialogic communication with their target groups online. To achieve this communication, they have identified five principles: dialogic loop, the usefulness of information, the generation of return visits, ease of the interface, and the rule of conservation of visitors.

According to Grunig, public relations focuses on concepts such as image, perception, messaging, reputation, branding, integrated marketing communication, return on investment (ROI), strategic communication, and corporate social responsibility projects. Public relations practitioners view the new digital media as a revolutionary force that changes the way of thinking and shapes public relations practices. Therefore, organizations also provide public relations practices, marketing activities, and other communications through social networks. This is why Twitter has emerged as an important social network application.

Twitter has been chosen for three reasons: 1) It is the most widely used social media channel by global companies. 2) It offers many useful features such as user tagging (mention), hashtags, media, and links for dialogic communication. 3) Almost all institutions' Twitter pages can be accessed by any user.

In the scope of the research; firstly, it has been revealed to what extent dialogic communication, which is a public relations approach, is used in the communications of climate actors. Then, the participation of the target audience in the actors' dialogic communications has been examined. Secondly, the actors' communications have been researched in the context of Grunig-Hunt's four public relations models. Lastly, it has been revealed what topics are discussed in the environmental and climate discussions in Turkey. Climate change communication is an area that has not yet been studied much in our country, despite being featured in many studies from abroad. It is expected that this study will provide an academic orientation in the field of climate change communication in this context.

In this study, multiple research approaches have been used. Data has been defined through content analysis and different variables have been derived from the data. The data has been brought together within the framework of specific concepts and themes. By making rule-based filters on the data obtained from the Twitter application, new variables are generated. This approach enables effective content analysis for environments with fast data flows such as Twitter, and provides a rule-based approach for evaluating dialogic communication and the four public relations models for large data sets. Finally, it has been revealed what themes the shares of environmental civil society organizations in 2020-2021 have been framed within and what the topic distribution is. In this context, the Latent Dirichlet Allocation (LDA) method, which is one of the probabilistic topic modeling approaches, has been used. It is thought that this research offers a pioneering and innovative approach in the context of adapting new technologies to the field of public relations.

In the research, it has been determined that the key dialogic principle for both civil society organizations and government agencies is "Generation of Return Visits" Organizations achieve this by sharing "sites providing additional information." Secondly, the principle of "Usefulness of Information" is given priority, which is done by organizations through their "photo" shares. In the "Conservation of Visitors" criterion, it was found that both actor groups prioritize "sharing their own websites," and that civil society organizations share more "social network shares" than government agencies. Clear differences have been observed in the usage of the principle of "Dialogic Loop" by organizations. While civil society organizations use the features of "answering users" and "using hashtags" more, government agencies use the feature of "user tagging" more. In the research, where public participation in the dialogic communication of organizations is evaluated, it was found that there is a strong relationship between the usage of dialogic communication principles of organizations and public participation. In the research conducted within the scope of Grunig's four public relations models, it was observed that civil society organizations and government agencies use different models in their Twitter usage. Both civil society organizations and government agencies prioritize the "public information" model. The "symmetric" model is the least used model by climate actors. Both actor groups use the "public information", "asymmetric", "press agency" and "symmetric" models in order. In the shares on environment and climate change in Turkey, it is observed that they are grouped into 9 main headings in Twitter environment. "Biodiversity," "climate," and "sustainability" themes are found to be more prominent than other themes.

**Keywords:** Public relations, climate change communication, climate communication, climate crisis, environmental communication, dialogic communication, Grunig-Hunt’s four PR models, topic modeling, latent dirichlet distinction, text classification, computational social sciences, Twitter, non-governmental organizations, ministries
