# ÖNSÖZ {-}


“Halkla İlişkiler ve İklim Değişikliği: Bakanlıkların ve STK'ların Twitter Üzerindeki Halkla İlişkiler Faaliyetlerinin Karşılaştırılması” adlı bu çalışmada, iklim krizi ve çevre konularındaki iklim aktörlerinin Twitter uygulamasında diyalojik ilkeleri nasıl kullandığı, diyalojik ilkeler bağlamında hedef gruplarının katılımı, iklim aktörlerinin Grunig ve Hunt'un dört halkla ilişkiler modeline göre iletişimlerini nasıl konumlandırdığı araştırılmaktadır. Ayrıca, çevre ve iklim değişikliği konularında sorun olarak görülen konular ortaya çıkarılmayı amaçlamaktadır.

Çalışmam sırasında bilgi ve tecrübelerini benimle paylaşan, yol gösteren, desteğini esirgemeyen değerli tez danışmanım Sayın Prof. Dr. Yeşim Güçdemir'e içten teşekkürlerimi sunarım. 

Hayatımın her aşamasında destek olan babam Fevzi Günay, annem Elif Günay, ablam Uzman Ebe Ph.D. Ümmügülsüm Günay'a da içten teşekkürlerimi sunarım. Akademik yaşantım boyunca hiç yalnız bırakmayan, klavyemden ve kucağımdan aşağı inmeyen kedim Mestan'a, diğer kedilerim Elia'ya ve Mia'ya da çok teşekkürlerimi ve sevgilerimi sunarım. 

İSTANBUL, 2022
KEMAL GÜNAY

